'use client'
import { useState } from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [isSidebarVisible, setSidebarVisible] = useState(true);

  const toggleSidebar = () => {
    setSidebarVisible((prev) => !prev);
  };

  return (
    <html lang="en">
      <body className={inter.className} style={{ overflow: 'hidden' }}>
        <Navbar />
        <div className="flex mt-4">
          <div
            className={`w-[12.5rem] sidebar ${
              isSidebarVisible ? 'visible' : ''
            }`}
          >
            <Sidebar />
          </div>
          <div className="w-[82rem] bg-[#1a1820] rounded-tl-xl">{children}</div>
        </div>
        <button className="toggle-btn sm:hidden" onClick={toggleSidebar}>
          Toggle Sidebar
        </button>
      </body>
    </html>
  );
}
