import axios from "axios";

export const ak = "api_key=fbd711827d344f731ebe3d8d09dd44e2";

export const BASE_URL = "https://api.themoviedb.org/3";
const TMDB_TOKEN =
  "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmYmQ3MTE4MjdkMzQ0ZjczMWViZTNkOGQwOWRkNDRlMiIsIm5iZiI6MTY5NDM2MDUyMy4zMjcwMDAxLCJzdWIiOiI2NGZkZTNjYmZmYzlkZTBlZTIwODAyNDkiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.kjM5ld-m5w8tV99Xm9ykwGdV88FFvkYboyOvTt1L1Rk";

const headers = {
  Authorization: "bearer " + TMDB_TOKEN,
};

export const fetchDataFromApi = async (url, params) => {
  try {
    const { data } = await axios.get(BASE_URL + url, {
      headers,
      params,
    });
    return data;
  } catch (err) {
    console.log(err);
    return err;
  }
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
